Pandas- It is an open source , BSD-licensed library providing data aalysis tools and data structures

In [3]:
!pip install pandas
import pandas as pd
import numpy as np

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Coumn4"])

In [5]:
df.head()

      Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [6]:
# prints last 5 records
df.tail()

      Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Coumn4   5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes

In [8]:
df.describe()

         Column1    Column2    Column3     Coumn4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [9]:
## Indexing of elements
# columnname, rowindex [loc] and rowindex columnindex number[iloc] (index location)
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Coumn4     3
Name: Row1, dtype: int64

In [10]:
df[['Column1','Column2','Column3' ]]

      Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [11]:

## Check the type
# Data series: one row or one column
# Data table: atleast more tha one row and column

type(df.loc['Row1'])

pandas.Series

In [12]:
type(df.loc[['Row1', 'Row2']])

pandas.DataFrame

In [13]:
# Take the elements from the Column2 and Row2
df.iloc[1:,1:]

      Column2  Column3  Coumn4
Row2        5        6       7
Row3        9       10      11
Row4       13       14      15
Row5       17       18      19

In [14]:
#convert Dataframes into array
df.iloc[0:,0:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
# each value and its counts
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [16]:
#checks if null value exists
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Coumn4     0
dtype: int64

In [17]:
df.isnull()

      Column1  Column2  Column3  Coumn4
Row1    False    False    False   False
Row2    False    False    False   False
Row3    False    False    False   False
Row4    False    False    False   False
Row5    False    False    False   False

In [18]:
#no duplicates
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [19]:
df>2

      Column1  Column2  Column3  Coumn4
Row1    False    False    False    True
Row2     True     True     True    True
Row3     True     True     True    True
Row4     True     True     True    True
Row5     True     True     True    True

Part-2

In [20]:
from io import StringIO
import pandas as pd

In [21]:
#adding info from kaggle
df= pd.read_csv('mercedesbenz.csv')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), str(8)
memory usage: 12.1 MB

In [23]:
df.describe()

,ID,X10,X11,X12,X13,X14,X15,X16,X17,X18,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4211.039202,0.019007,0.000238,0.074364,0.061060,0.427893,0.000713,0.002613,0.008791,0.010216,...,0.325968,0.049656,0.311951,0.019244,0.011879,0.008078,0.008791,0.000475,0.000713,0.001663
std,2423.078926,0.136565,0.015414,0.262394,0.239468,0.494832,0.026691,0.051061,0.093357,0.100570,...,0.468791,0.217258,0.463345,0.137399,0.108356,0.089524,0.093357,0.021796,0.026691,0.040752
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2115.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4202.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6310.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8416.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
data = "col1, col2, col3 \n" "x,y,z \n" "a,b,c \n"

In [25]:
#in memory file format
StringIO(data)

In [26]:
pd.read_csv(StringIO(data), dtype='object')

  col1  col2  col3
0    x     y     z
1    a     b     c

In [27]:
df = pd.read_csv(StringIO(data), usecols=["col1", "col2"], skipinitialspace=True)
df

  col1 col2
0    x    y
1    a    b

In [28]:
#converts back to csv and no indexing now
df.to_csv("data", index= False)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      str
 1   col2    2 non-null      str
dtypes: str(2)
memory usage: 164.0 bytes

In [30]:
data = "col1,col2,col3 \n" "x,y,z \n" "a,b,c \n"

In [31]:
df=pd.read_csv(StringIO(data), dtype={'x':int, 'b':float})

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      str
 1   col2    2 non-null      str
 2   col3    2 non-null      str
dtypes: str(3)
memory usage: 180.0 bytes

In [33]:
df.dtypes

col1     str
col2     str
col3     str
dtype: object

In [34]:
df=pd.read_csv(StringIO(data), index_col=0)
df

     col2 col3
col1
x       y    z
a       b    c

In [35]:
#use index cols and usecols
data= ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')

In [36]:
pd.read_csv(StringIO(data), usecols=['a','b', 'c'], index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

Read Json to CSV

In [47]:

data = {"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1": "Team lead", "Title2": "Sr Developer"}]}
df = pd.DataFrame([data])
df

,employee_name,email,job_profile
0,James,james@gmail.com,"[{'title1': 'Team lead', 'Title2': 'Sr Develop..."

In [48]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [49]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [50]:
# convert Json to csv
df.to_csv('wine.csv')

In [51]:
# convert Json to different json formats
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},"8":{"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},"9":{"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},"10":{"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},"11":{"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},"12":{"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},"13":{"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},"14":{"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},"15":{"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},"16":{"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},"17":{"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},"18":{"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},"19":{"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},"20":{"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},"21":{"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},"22":{"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},"23":{"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},"24":{"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},"25":{"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},"26":{"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},"27":{"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},"28":{"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},"29":{"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},"30":{"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},"31":{"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},"32":{"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},"33":{"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},"34":{"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},"35":{"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},"36":{"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},"37":{"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},"38":{"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},"39":{"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},"40":{"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},"41":{"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},"42":{"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},"43":{"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},"44":{"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},"45":{"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},"46":{"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},"47":{"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},"48":{"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},"49":{"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},"50":{"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},"51":{"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},"52":{"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},"53":{"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},"54":{"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},"55":{"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},"56":{"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},"57":{"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},"58":{"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},"59":{"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},"60":{"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},"61":{"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},"62":{"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},"63":{"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},"64":{"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},"65":{"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},"66":{"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},"67":{"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},"68":{"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},"69":{"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},"70":{"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},"71":{"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},"72":{"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},"73":{"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},"74":{"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},"75":{"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},"76":{"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},"77":{"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},"78":{"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},"79":{"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},"80":{"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},"81":{"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},"82":{"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},"83":{"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},"84":{"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},"85":{"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},"86":{"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},"87":{"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},"88":{"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},"89":{"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},"90":{"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},"91":{"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},"92":{"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},"93":{"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},"94":{"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},"95":{"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},"96":{"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},"97":{"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},"98":{"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},"99":{"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},"100":{"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},"101":{"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},"102":{"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},"103":{"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},"104":{"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},"105":{"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},"106":{"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},"107":{"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},"108":{"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},"109":{"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},"110":{"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},"111":{"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},"112":{"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},"113":{"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},"114":{"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},"115":{"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},"116":{"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},"117":{"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},"118":{"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},"119":{"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},"120":{"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},"121":{"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},"122":{"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},"123":{"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},"124":{"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},"125":{"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},"126":{"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},"127":{"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},"128":{"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},"129":{"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},"130":{"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},"131":{"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},"132":{"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},"133":{"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},"134":{"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},"135":{"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},"136":{"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},"137":{"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},"138":{"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},"139":{"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},"140":{"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53,"9":0.75,"10":4.6,"11":0.77,"12":2.31,"13":600},"141":{"0":3,"1":13.36,"2":2.56,"3":2.35,"4":20.0,"5":89,"6":1.4,"7":0.5,"8":0.37,"9":0.64,"10":5.6,"11":0.7,"12":2.47,"13":780},"142":{"0":3,"1":13.52,"2":3.17,"3":2.72,"4":23.5,"5":97,"6":1.55,"7":0.52,"8":0.5,"9":0.55,"10":4.35,"11":0.89,"12":2.06,"13":520},"143":{"0":3,"1":13.62,"2":4.95,"3":2.35,"4":20.0,"5":92,"6":2.0,"7":0.8,"8":0.47,"9":1.02,"10":4.4,"11":0.91,"12":2.05,"13":550},"144":{"0":3,"1":12.25,"2":3.88,"3":2.2,"4":18.5,"5":112,"6":1.38,"7":0.78,"8":0.29,"9":1.14,"10":8.21,"11":0.65,"12":2.0,"13":855},"145":{"0":3,"1":13.16,"2":3.57,"3":2.15,"4":21.0,"5":102,"6":1.5,"7":0.55,"8":0.43,"9":1.3,"10":4.0,"11":0.6,"12":1.68,"13":830},"146":{"0":3,"1":13.88,"2":5.04,"3":2.23,"4":20.0,"5":80,"6":0.98,"7":0.34,"8":0.4,"9":0.68,"10":4.9,"11":0.58,"12":1.33,"13":415},"147":{"0":3,"1":12.87,"2":4.61,"3":2.48,"4":21.5,"5":86,"6":1.7,"7":0.65,"8":0.47,"9":0.86,"10":7.65,"11":0.54,"12":1.86,"13":625},"148":{"0":3,"1":13.32,"2":3.24,"3":2.38,"4":21.5,"5":92,"6":1.93,"7":0.76,"8":0.45,"9":1.25,"10":8.42,"11":0.55,"12":1.62,"13":650},"149":{"0":3,"1":13.08,"2":3.9,"3":2.36,"4":21.5,"5":113,"6":1.41,"7":1.39,"8":0.34,"9":1.14,"10":9.4,"11":0.57,"12":1.33,"13":550},"150":{"0":3,"1":13.5,"2":3.12,"3":2.62,"4":24.0,"5":123,"6":1.4,"7":1.57,"8":0.22,"9":1.25,"10":8.6,"11":0.59,"12":1.3,"13":500},"151":{"0":3,"1":12.79,"2":2.67,"3":2.48,"4":22.0,"5":112,"6":1.48,"7":1.36,"8":0.24,"9":1.26,"10":10.8,"11":0.48,"12":1.47,"13":480},"152":{"0":3,"1":13.11,"2":1.9,"3":2.75,"4":25.5,"5":116,

In [52]:

df.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},{"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},{"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},{"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},{"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},{"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},{"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},{"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},{"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},{"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},{"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},{"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},{"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},{"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},{"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},{"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},{"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},{"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},{"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},{"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},{"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},{"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},{"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},{"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},{"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},{"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},{"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},{"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},{"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},{"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},{"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},{"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},{"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},{"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},{"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},{"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},{"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},{"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},{"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},{"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},{"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},{"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},{"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},{"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},{"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},{"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},{"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},{"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},{"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},{"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},{"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},{"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},{"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},{"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},{"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},{"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},{"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},{"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},{"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},{"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},{"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},{"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},{"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},{"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},{"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},{"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},{"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},{"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},{"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},{"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},{"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},{"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},{"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},{"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},{"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},{"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},{"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},{"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},{"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},{"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},{"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},{"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},{"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},{"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},{"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},{"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},{"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},{"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},{"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},{"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},{"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},{"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},{"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},{"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},{"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},{"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},{"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},{"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},{"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},{"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},{"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},{"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},{"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},{"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},{"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},{"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},{"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},{"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},{"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},{"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},{"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},{"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},{"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},{"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},{"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},{"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},{"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},{"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},{"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},{"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},{"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},{"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},{"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},{"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},{"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},{"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},{"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},{"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},{"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},{"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},{"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},{"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},{"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},{"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53,"9":0.75,"10":4.6,"11":0.77,"12":2.31,"13":600},{"0":3,"1":13.36,"2":2.56,"3":2.35,"4":20.0,"5":89,"6":1.4,"7":0.5,"8":0.37,"9":0.64,"10":5.6,"11":0.7,"12":2.47,"13":780},{"0":3,"1":13.52,"2":3.17,"3":2.72,"4":23.5,"5":97,"6":1.55,"7":0.52,"8":0.5,"9":0.55,"10":4.35,"11":0.89,"12":2.06,"13":520},{"0":3,"1":13.62,"2":4.95,"3":2.35,"4":20.0,"5":92,"6":2.0,"7":0.8,"8":0.47,"9":1.02,"10":4.4,"11":0.91,"12":2.05,"13":550},{"0":3,"1":12.25,"2":3.88,"3":2.2,"4":18.5,"5":112,"6":1.38,"7":0.78,"8":0.29,"9":1.14,"10":8.21,"11":0.65,"12":2.0,"13":855},{"0":3,"1":13.16,"2":3.57,"3":2.15,"4":21.0,"5":102,"6":1.5,"7":0.55,"8":0.43,"9":1.3,"10":4.0,"11":0.6,"12":1.68,"13":830},{"0":3,"1":13.88,"2":5.04,"3":2.23,"4":20.0,"5":80,"6":0.98,"7":0.34,"8":0.4,"9":0.68,"10":4.9,"11":0.58,"12":1.33,"13":415},{"0":3,"1":12.87,"2":4.61,"3":2.48,"4":21.5,"5":86,"6":1.7,"7":0.65,"8":0.47,"9":0.86,"10":7.65,"11":0.54,"12":1.86,"13":625},{"0":3,"1":13.32,"2":3.24,"3":2.38,"4":21.5,"5":92,"6":1.93,"7":0.76,"8":0.45,"9":1.25,"10":8.42,"11":0.55,"12":1.62,"13":650},{"0":3,"1":13.08,"2":3.9,"3":2.36,"4":21.5,"5":113,"6":1.41,"7":1.39,"8":0.34,"9":1.14,"10":9.4,"11":0.57,"12":1.33,"13":550},{"0":3,"1":13.5,"2":3.12,"3":2.62,"4":24.0,"5":123,"6":1.4,"7":1.57,"8":0.22,"9":1.25,"10":8.6,"11":0.59,"12":1.3,"13":500},{"0":3,"1":12.79,"2":2.67,"3":2.48,"4":22.0,"5":112,"6":1.48,"7":1.36,"8":0.24,"9":1.26,"10":10.8,"11":0.48,"12":1.47,"13":480},{"0":3,"1":13.11,"2":1.9,"3":2.75,"4":25.5,"5":116,"6":2.2,"7":1.28,"8":0.26,"9":1.56,"10":7.1,"11":0.61,"12":1.33,"13":425},{"0":3,"1":13.23,"2":3.3,"3":2.28,"4":18.5,"5":98,"6":1.8,"7":0.83,"8":0.61,"9":1.87,"10":10.52,"11":0.56,"12":1.51,"13":675},{"0":3,"1":12.58,"2":1.29,"3":2.1,"4":20.0,"5":103,"6":1.48,"7":0.58,"8":0.53,"9":1.4,"10":7.6,"11":0.58,"12":1.55,"13":640},{"0":3,"1":13.17,"2":5.19,"3":2.32,"4":22.0,"5":93,"6":1.74,"7":0.63,"8":0.61,"9":1.55,"10":7.9,"11":0.6,"12":1.48,"13":725},{"0":3,"1":13.84,"2":4.12,"3":2.38,"4":19.5,"5":89,"6":1.8,"7":0.83,"8":0.48,"9":1.56,"10":9.01,"11":0.57,"12":1.64,"13":480},{"0":3,"1":12.45,"2":3.03,"3":2.64,"4":27.0,"5":97,"6":1.9,"7":0.58,"8":0.63,"9":1.14,"10":7.5,"11":0.67,"12":1.73,"13":880},{"0":3,"1":14.34,"2":1.68,"3":2.7,"4":25.0,"5":98,"6":2.8,"7":1.31,"8":0.53,"9":2.7,"10":13.0,"11":0.57,"12


Reading HTML content

In [55]:
!pip install lxml
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url)

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------- ----- 3.4/4.0 MB 17.8 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 15.8 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

In [ ]:
from io import StringIO
import requests

url_mcc = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

response = requests.get(url_mcc, headers=headers)

#the heading 'country' or 'Mobile network codes' matches it picks up from there
dfs = pd.read_html(StringIO(response.text), match="Country", header=0)

dfs[0].head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

In [60]:
dfs[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

Reading Excel Files

In [67]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dishi neekhra\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [68]:
df_excel=pd.read_excel('Excel_Sample.xlsx')
df_excel.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA


Pickling
: All pandas objects are equipped with to_pickle methods which use Python’s cPickle module to save data structures to disk using the pickle format.

In [69]:
df_excel.to_pickle('Excel_Sample.xlsx')

In [70]:

df=pd.read_pickle('Excel_Sample.xlsx')
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA